// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenRemote_Sender_Ui

#include "../ui.h"

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Exit = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Exit, 36);
    lv_obj_set_height(ui_Exit, 36);
    lv_obj_set_x(ui_Exit, 2);
    lv_obj_set_y(ui_Exit, 2);
    lv_obj_add_flag(ui_Exit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Exit, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Exit, lv_color_hex(0xC14022), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Exit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Menu);
    lv_obj_set_width(ui_Panel1, 278);
    lv_obj_set_height(ui_Panel1, 36);
    lv_obj_set_x(ui_Panel1, 40);
    lv_obj_set_y(ui_Panel1, 2);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xBFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xBFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExitLabel = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_ExitLabel, 36);
    lv_obj_set_height(ui_ExitLabel, 16);
    lv_obj_set_x(ui_ExitLabel, 2);
    lv_obj_set_y(ui_ExitLabel, 12);
    lv_label_set_text(ui_ExitLabel, "Exit");
    lv_obj_set_style_text_color(ui_ExitLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ExitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ExitLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuLabel = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_MenuLabel, 90);
    lv_obj_set_height(ui_MenuLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuLabel, 125);
    lv_obj_set_y(ui_MenuLabel, 12);
    lv_label_set_text(ui_MenuLabel, "Hauptmenu");

    ui_Button1 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button1, 316);
    lv_obj_set_height(ui_Button1, 36);
    lv_obj_set_x(ui_Button1, 2);
    lv_obj_set_y(ui_Button1, 42);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 16);
    lv_obj_set_y(ui_Label1, 52);
    lv_label_set_text(ui_Label1, "Servos");

    lv_obj_add_event_cb(ui_Exit, ui_event_Exit, LV_EVENT_ALL, NULL);

}
